name: PlatformIO CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [examples/Button_SL-example/Button_SL-example.ino]
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip setuptools
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio ci --lib="." --board=uno --board=esp-wrover-kit --board=d1_mini
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
